/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Barrel.glb -T 
Files: Barrel.glb [25.22KB] > F:\My Documents\Sites games\ice-slide\public\models\Barrel-transformed.glb [3.19KB] (87%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelBarrel(props) {
  const { nodes, materials } = useGLTF('models/Barrel-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.barrel_1.geometry} material={materials.cloth} />
      <mesh geometry={nodes.barrel_1_1.geometry} material={materials.metal} />
    </group>
  )
}

useGLTF.preload('models/Barrel-transformed.glb')
