/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Gear.glb -T 
Files: Gear.glb [15.97KB] > F:\My Documents\Sites games\ice-slide\public\models\Gear-transformed.glb [3.03KB] (81%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelGear(props) {
  const { nodes, materials } = useGLTF('models/Gear-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.lambert2SG} />
    </group>
  )
}

useGLTF.preload('models/Gear-transformed.glb')
