/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Iceberg.glb -T 
Files: Iceberg.glb [58.81KB] > F:\My Documents\Sites games\ice-slide\public\models\Iceberg-transformed.glb [31.26KB] (47%)
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'


export function ModelIceberg({ bobHeight = 2, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('models/Iceberg-transformed.glb')
  // Random phase offset so each instance bobs out of sync
  const phase = useMemo(() => Math.random() * Math.PI * 2, [])
  useFrame((state) => {
    if (group.current) {
      group.current.position.y = Math.sin(state.clock.getElapsedTime() * 1.2 + phase) * bobHeight
    }
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.Platonic} />
    </group>
  )
}

useGLTF.preload('models/Iceberg-transformed.glb')
