/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ..\GLB\Igloo Open.glb --output output\Igloo Open.js --keepnames --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/Google/Models/Igloo Open.glb`;

export function ModelGoogleIglooOpen(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh name="Node" castShadow receiveShadow geometry={nodes.Node.geometry} material={materials.lambert9SG} />
      <mesh name="Sphere" castShadow receiveShadow geometry={nodes.Sphere.geometry} material={materials.lambert9SG} position={[0, 1.355, 0]} />
    </group>
  )
}

useGLTF.preload(link)
