/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Inflatable Water Tube.glb -T 
Files: Inflatable Water Tube.glb [152.94KB] > F:\My Documents\Sites games\ice-slide\public\models\Inflatable Water Tube-transformed.glb [11.07KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelInflatableWaterTube(props) {
  const { nodes, materials } = useGLTF('models/Inflatable Water Tube-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1128786684.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group299848747.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1539798531.geometry} material={materials.mat23} />
    </group>
  )
}

useGLTF.preload('models/Inflatable Water Tube-transformed.glb')
