/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Pluto.glb -T 
Files: Pluto.glb [572.89KB] > F:\My Documents\Sites games\ice-slide\public\models\Pluto-transformed.glb [84.79KB] (85%)
Author: ThisIsntAPerson (https://sketchfab.com/ThisIsntAPerson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pluto-b37ea9b0161943e6bb8ba9fee8bc80b1
Title: Pluto
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function ModelPluto(props) {
  const { scene } = useGLTF('models/Pluto-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null} scale={400} position={[0, -2, 0]}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_5.geometry} material={materials.hr_pluto_mat} skeleton={nodes.Object_5.skeleton} scale={0.01} />
    </group>
  )
}

useGLTF.preload('models/Pluto-transformed.glb')
