/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Snowman.glb -T 
Files: Snowman.glb [116.53KB] > F:\My Documents\Sites games\ice-slide\public\models\Snowman-transformed.glb [22.21KB] (81%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelSnowman(props) {
  const { nodes, materials } = useGLTF('models/Snowman-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Snowman.geometry} material={materials.Snowman} position={[0, 2, 0]} rotation={[-1.577, 0.056, 0.139]} scale={100} />
    </group>
  )
}

useGLTF.preload('models/Snowman-transformed.glb')
