/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ToonDogHead.glb -T 
Files: ToonDogHead.glb [313.44KB] > F:\My Documents\Sites games\ice-slide\public\models\ToonDogHead-transformed.glb [29.95KB] (90%)
Author: Smooth (https://sketchfab.com/smoothviews)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dog-head-1af917cff4384edf9ef692d59c1c95dc
Title: Dog Head
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelToonDogHead(props) {
  const { nodes, materials } = useGLTF('models/ToonDogHead-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface1_lambert4_0.geometry} material={materials.PaletteMaterial001} />
    </group>
  )
}

useGLTF.preload('models/ToonDogHead-transformed.glb')
