/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Wheel.glb -T 
Files: Wheel.glb [26.67KB] > F:\My Documents\Sites games\ice-slide\public\models\Wheel-transformed.glb [6.4KB] (76%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelWheel(props) {
  const { nodes, materials } = useGLTF('models/Wheel-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Wheel.geometry} material={materials['Atlas.037']} scale={100} />
    </group>
  )
}

useGLTF.preload('models/Wheel-transformed.glb')
